<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UeDq8_y' shared service.

return $this->privates['.service_locator.UeDq8_y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pictureProduitRepository' => ['privates', 'App\\Repository\\PictureProduitRepository', 'getPictureProduitRepositoryService.php', true],
], [
    'pictureProduitRepository' => 'App\\Repository\\PictureProduitRepository',
]);
