<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3pxqCHj' shared service.

return $this->privates['.service_locator.3pxqCHj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.3pxqCHj.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.3pxqCHj": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'encoder' => '?',
    'user' => 'App\\Entity\\User',
]);
