<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tJkdhm5' shared service.

return $this->privates['.service_locator.tJkdhm5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\PictureProduitController::delete' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\PictureProduitController::edit' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\PictureProduitController::index' => ['privates', '.service_locator.UeDq8_y', 'get_ServiceLocator_UeDq8YService.php', true],
    'App\\Controller\\PictureProduitController::show' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\SecurityController::editUser' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.3pxqCHj', 'get_ServiceLocator_3pxqCHjService.php', true],
    'App\\Controller\\UserController::new' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\PictureProduitController:delete' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\PictureProduitController:edit' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\PictureProduitController:index' => ['privates', '.service_locator.UeDq8_y', 'get_ServiceLocator_UeDq8YService.php', true],
    'App\\Controller\\PictureProduitController:show' => ['privates', '.service_locator.JTx4eZ9', 'get_ServiceLocator_JTx4eZ9Service.php', true],
    'App\\Controller\\SecurityController:editUser' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.3pxqCHj', 'get_ServiceLocator_3pxqCHjService.php', true],
    'App\\Controller\\UserController:new' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
], [
    'App\\Controller\\CategoryController::delete' => '?',
    'App\\Controller\\CategoryController::edit' => '?',
    'App\\Controller\\PictureProduitController::delete' => '?',
    'App\\Controller\\PictureProduitController::edit' => '?',
    'App\\Controller\\PictureProduitController::index' => '?',
    'App\\Controller\\PictureProduitController::show' => '?',
    'App\\Controller\\SecurityController::editUser' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::edit' => '?',
    'App\\Controller\\UserController::new' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\CategoryController:delete' => '?',
    'App\\Controller\\CategoryController:edit' => '?',
    'App\\Controller\\PictureProduitController:delete' => '?',
    'App\\Controller\\PictureProduitController:edit' => '?',
    'App\\Controller\\PictureProduitController:index' => '?',
    'App\\Controller\\PictureProduitController:show' => '?',
    'App\\Controller\\SecurityController:editUser' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:edit' => '?',
    'App\\Controller\\UserController:new' => '?',
    'App\\Controller\\UserController:show' => '?',
]);
