<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.model_describers.object' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/ModelDescriber/ModelDescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php';

return $this->privates['nelmio_api_doc.model_describers.object'] = new \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber(($this->privates['property_info'] ?? $this->load('getPropertyInfoService.php')), ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
