<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.route_describers.fos_rest' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/RouteDescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/RouteDescriberTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/FosRestDescriber.php';

return $this->privates['nelmio_api_doc.route_describers.fos_rest'] = new \Nelmio\ApiDocBundle\RouteDescriber\FosRestDescriber(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
