<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAsSOexb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAsSOexb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAsSOexb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAsSOexb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAsSOexb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AsSOexb',
    'container.build_id' => 'e5b03a27',
    'container.build_time' => 1564433285,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAsSOexb');
