register:
    path: /register
    controller: App\Controller\SecurityController::registration
    methods: POST


api:
    path: /api
    controller: App\Controller\SecurityController::api

login_check:
    path:     /login_check
    methods:  [POST]